export const GET_STORED_INPUTS = 'GET_STORED_INPUTS';

export const UPDATE_VISIBLE_TEXT_INPUT = 'UPDATE_VISIBLE_TEXT_INPUT';

export const IMPORT_JSON = 'IMPORT_JSON';

export const OPEN_IMPORT_JSON = 'OPEN_IMPORT_JSON';

export const CLOSE_IMPORT_JSON = 'CLOSE_IMPORT_JSON';
